### ISSUE TITLE
`calcuateHash` strips two leading zeros resulting in incorrect hash value

### ISSUE THREAD

**Issue by quapka** [eu-digital-green-certificates/dgca-businessrule-service#17]
Please, see the [#53 in `dgc-lib`](https://github.com/eu-digital-green-certificates/dgc-lib/issues/53) as the exact same bug is present in [here](https://github.com/eu-digital-green-certificates/dgca-businessrule-service/blob/128e116285831750de51fe7b67202165c9c779e2/src/main/java/eu/europa/ec/dgc/businessrule/utils/BusinessRulesUtils.java#L44) and also [here](https://github.com/eu-digital-green-certificates/dgca-businessrule-service/blob/6e87451612437324c03287cb6aabd31d7d501612/src/main/java/eu/europa/ec/dgc/businessrule/service/GatewayDataDownloadBtpServiceImpl.java#L267).

**Comment by a-trzewik** [comment]
This is indeed a problem.
We will use calculateHash from dgc-lib. The implementation will be updated in dgc-lib.

**Comment by quapka** [comment]
Yes, overall there are four occurrences of this in three projects (I've created a issue in each of them), so please make sure to fix _all_ of them.
```bash
--> ag '== 63'
dgc-lib/src/main/java/eu/europa/ec/dgc/utils/CertificateUtils.java
144:        if (hexString.length() == 63) {

dgc-gateway/src/main/java/eu/europa/ec/dgc/gateway/restapi/filter/CertificateAuthenticationFilter.java
110:                if (hexString.length() == 63) {

dgca-businessrule-service/src/main/java/eu/europa/ec/dgc/businessrule/utils/BusinessRulesUtils.java
48:        if (hexString.length() == 63) {

dgca-businessrule-service/src/main/java/eu/europa/ec/dgc/businessrule/service/GatewayDataDownloadBtpServiceImpl.java
272:            if (hexString.length() == 63) {
```
