### ISSUE TITLE
TLS1.2 for Maven

### ISSUE THREAD

**Issue by psavva** [eu-digital-green-certificates/dgca-businessrule-service#21]
As of 18th June, TLS1.1 was been deprecated.

https://central.sonatype.org/faq/tls-info/

Can I suggest we do the following:
Create a folder .mvn
Create a file .\mvn\jvm.config
with the content: "-Dhttps.protocols=TLSv1.2"

I can issue a PR to all the JAVA repos if you agree.  This will help with controlling the TLS versions used in the repos.

Best Regards
Panayiotis Savva

**Comment by a-trzewik** [comment]
This is only build issue on older jdk so it concern only limited group of users.
This can be easy set by local settings.
I remove the "bug" label because it is reserved only for wrong functionality

**Comment by a-trzewik** [comment]
It is very old deprecated issue. We decided not to set it because it could make problems in our build systems
